import { ChakraProvider } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Slide from "../components/Slide";
import { Banner, getInfoBanner } from "../lib/hero";
import styles from "../styles/Home.module.css";

// export interface HomeProps {
//   data: Banner;
// }

export default function Home() {
  return (
    <ChakraProvider>
      <Head>
        <title>Observatorio :: Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero></Hero>
      <Slide></Slide>

    </ChakraProvider>
  );
}

export async function getStaticProps() {
  const [data] = await getInfoBanner();

  console.log("🚀 ~ file: index.tsx:41 ~ getStaticProps ~  data", data);

  return {
    props: {
      data,
    },
  };
}
